### PR TITLE
Add tested libraries of @christiankral to release notes

### PR DESCRIPTION
**Pull request by christiankral**
- Change list of libraries to table (to have a better overview)
- Add some more rested libraries

### CODE REVIEW

**Comment by beutlich** [comment]
Thanks for the effort both in testing and converting to table format.

grafik

I have two remarks though:

1. Previously we did not link to the libraries. (I only linked to the [Buildings issue](https://github.com/lbl-srg/modelica-buildings/issues/1789) since it is a dedicated issue reporting the test). I am in favour of removing all links to the reposizories to avoid promoting libraries. In the release notes it should be sufficient to just tell name and version.

1. Wouldn't it be enough to tell the test tool Dymola 2020/2020x above the table? I doubt there is much difference in testing with 2020 or 2020x.

**Comment by christiankral** [comment]
> 1. Previously we did not link to the libraries. (I only linked to the Buildings issue since it is a dedicated issue reporting the test). I am in favour of removing all links to the reposizories to avoid promoting libraries. In the release notes it should be sufficient to just tell name and version.

I did intentionally not add a link to the commercial EDrives library, so that there is no direct promotion. I only provided a link to the open source libraries. However, it is perfectly fine with me to remove all the links.

> 2. Wouldn't it be enough to tell the test tool Dymola 2020/2020x above the table? I doubt there is much difference in testing with 2020 or 2020x.

If it does not make a great difference whether the test was performed with Dymola 2020 or 2020x, I am OK with using Dymola 2020/2020x.

**Comment by christiankral** [comment]
image

**Comment by christiankral** [comment]
> The tests have been performed with Dymola 2020x:

Now I understand: You want Dymola not listed in the table:

image

**Pull request merged**
